config/routes.rb
Rails.application.routes.draw do
  namespace :conversion do
    resources :missions 
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mission.rb
class Mission < ApplicationRecord
    after_create do
        require "uri"
        require "net/http"
        url = URI("https://api.fastforex.io/fetch-one?from=#{currency1}&to=#{currency2}&api_key=a802733868-8a8100651e-radp1s")
        https = Net::HTTP.new(url.host, url.port)
        https.use_ssl = true
        request = Net::HTTP::Get.new(url)
        response = JSON.parse(https.request(request).body)
        @value  = response["result"].values
        update(currency1: "#{currency1}", currency2: "#{currency2}", rate: @value[0])
    end
    validates :currency1, :currency2, presence: true
    validates_format_of :currency1, :currency2, with: /\A[A-Z]{3}\z/, message: "geçersiz kod"
    #validates :currency1, inclusion: { in: %w(TRY USD EUR),
     #   message: "%{value} is not a valid size" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversion/missions_controller.rb
class Conversion::MissionsController < ApplicationController
 
  def index
    @mission = Mission.all
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(mission_params)
    if (@mission.save) 
      redirect_to  conversion_missions_path
    else
      render :new
    end
  end
  def destroy
    @mission = Mission.find(params[:id])
    @mission.destroy
    redirect_to conversion_missions_path
  end

  def mission_params
    params.require(:mission).permit(:currency1, :currency2, :rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/conversion/missions/index.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<h1>Home</h1>
<table border="1", class="table table-striped mt-2">
  <tr>
    <td>Currency1</td>
    <td>Currency2</td>
    <td>Rate</td>
    <td></td>
  </tr>
  <tr>
    <% @mission.each do |m| %>
      <td> <%= m.currency1 %> </td>
      <td> <%= m.currency2 %> </td>
      <td> <%= m.rate %> </td>
      <td> <%= button_to "Destroy", {action: "destroy", id: m.id}, method: :delete, class:"btn btn-outline-danger", data: { confirm: "Are you sure?" } %> </td>    
  </tr> 
  <%end%>
  <%=link_to "Save New Rate",new_conversion_mission_path%>
</table>

<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
  <script>
    function addDarkmodeWidget() {
      new Darkmode().showWidget();
    }
    window.addEventListener('load', addDarkmodeWidget);
  </script> 
  

app/views/conversion/missions/new.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


 <%= form_for [:conversion, @mission] do |f| %>
    <div class="form-row mt-5 ">
      <div class="col-md-4 mb-3 mx-auto">
        <%= f.label :currency1, "Currency1", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :currency1, class: "form-control is-valid", id:"validationTextarea" %>
        </div>

        <%= f.label :currency2, "Currency2", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :currency2, class: "form-control is-valid mb-3" %>
        </div>

        <div class="ml-3">
          <%= f.submit "Convert", class: "btn btn-default btn-primary" %>
        </div>  
      </div>
    </div>

 <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>